---
on:
    release:
        types:
            - published
jobs:
    build-n-publish:
        defaults:
            run:
                working-directory: python-cli
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: pip install poetry
            - run: echo "ref is $GITHUB_REF"
            - run: poetry version ${GITHUB_REF:10}
            - run: poetry build
            - run: pip install twine
            - run: twine upload dist/* -ualex-treebeard -p${{ secrets.PYPI_PASSWORD }}
            - uses: EndBug/add-and-commit@v7.0.0
              with:
                  author_name: github-actions
                  author_email: 41898282+github-actions[bot]@users.noreply.github.com
                  add: python-cli/pyproject.toml
                  branch: main
